# Generated by Django 4.1.2 on 2024-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymAIapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BicepCurlResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_time", models.DateTimeField(auto_now_add=True)),
                ("total_curls", models.IntegerField()),
                (
                    "form_errors",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON-encoded list of detected form errors",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Summary or detailed feedback on the bicep curl analysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_time"],
            },
        ),
    ]
