# Generated by Django 4.1.2 on 2024-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymAIapp", "0002_bicepcurlresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="bicepcurlresult",
            name="processed_video_filename",
            field=models.CharField(
                blank=True,
                help_text="Filename of the processed video",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bicepcurlresult",
            name="analysis_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp for when the analysis was conducted",
            ),
        ),
        migrations.AlterField(
            model_name="bicepcurlresult",
            name="total_curls",
            field=models.IntegerField(help_text="Total number of curls detected"),
        ),
    ]
