# Generated by Django 4.1.2 on 2024-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymAIapp", "0004_squatresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoulderLateralRaiseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp for when the analysis was conducted",
                    ),
                ),
                (
                    "total_reps",
                    models.IntegerField(
                        help_text="Total number of shoulder lateral raises detected"
                    ),
                ),
                (
                    "form_errors",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON-encoded list of detected form errors",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Summary or detailed feedback on the shoulder lateral raise analysis",
                    ),
                ),
                (
                    "processed_video_filename",
                    models.CharField(
                        blank=True,
                        help_text="Filename of the processed video",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_time"],
            },
        ),
    ]
